const juicy = [
      "Wat is het vreemdste dat je ooit in het openbaar hebt gedaan?",
      "Wat is iets beschamends dat je hebt gedaan en nooit aan iemand hebt verteld?",
      "Wat is het meest bizarre bericht dat je ooit hebt ontvangen?",
      "Wat is het meest cringy dat je ooit op sociale media hebt gezet?",
      "Hoeveel verandert jouw persoonlijkheid als je bij verschillende mensen bent?",
      "Wat is het aardigste dat iemand ooit voor jou heeft gedaan?",
      "Als iemand een boek over jou zou schrijven, hoe zou het heten?",
      "Geloof je in het hebben van één beste vriend?",
      "Hoe definieer jij schoonheid?",
      "Wat vind je de meest irritante eigenschap die iemand kan hebben?",
      "Wie vind jij dat geen beroemdheid zou moeten zijn?",
      "Wie was je meest onverwachte crush?",
      "Wanneer en waar was je eerste kus?",
      "Met wat voor type persoon zie jij jezelf uiteindelijk eindigen?",
      "Wat is jouw guilty pleasure-film of tv-show?",
      "Wat is jouw 'Romeinse Rijk'? (Iets waar je constant aan denkt).",
      "Wat is het beste roddeltje dat je ooit hebt gehoord?",
      "Welk deel van jouw sterrenbeeld herken je het meest in jezelf?",
      "Wat is jouw favoriete reisverhaal?",
      "Wat is het spannendste dat je ooit hebt gedaan?",
      "Wat is het meest illegale dat je ooit hebt gedaan?",
      "Heb je ooit iets gestolen? Wat was het?",
      "Heb je ooit een leugen verteld die gigantisch uit de hand liep?",
      "Wat is de ergste nachtmerrie die je ooit hebt gehad?",
      "Wat zou je doen als je 24 uur onzichtbaar zou zijn?",
      "Wat is het meest gênante moment dat je ooit in een romantische situatie hebt gehad?",
      "Heb je ooit een crush gehad op iemand die je absoluut niet zou moeten hebben?",
      "Wat is de meest gewaagde beslissing die je ooit hebt genomen?",
      "Heb je ooit een flirt volledig verkeerd geïnterpreteerd?",
      "Heb je ooit een date moeten faken om te ontsnappen?",
      "Heb je ooit een vriend verraden? Wat gebeurde er?",
      "Wat is het domste dat je hebt gedaan toen je dronken was?",
      "Heb je ooit een geheime relatie gehad?",
      "Wat is het raarste wat iemand ooit tegen je gezegd heeft?",
      "Heb je ooit een one-night stand gehad?",
      "Wat is de meest rare plek waar je ooit in slaap bent gevallen?",
      "Wat is het raarste dat je ooit online hebt gekocht?",
      "Wat is je grootste guilty pleasure qua eten?",
      "Wat is het meest gênante dat ooit op je telefoon stond?",
      "Heb je ooit een bericht gestuurd naar de verkeerde persoon? Wat gebeurde er?",
      "Wat is het raarste gerucht dat je ooit over jezelf hebt gehoord?",
      "Heb je ooit iemands telefoon doorgespit zonder dat diegene het wist?",
      "Wat is de gekste droom die je ooit hebt gehad?",
      "Wat is de stoutste leugen die je ooit hebt verteld?",
      "Wat is het meest risicovolle dat je ooit hebt gedaan?",
      "Heb je ooit een crush gehad op een leraar?",
      "Wat is het meest gênante dat je ouders ooit over je hebben ontdekt?",
      "Heb je ooit gedaan alsof je iemand niet kende terwijl je dat wel deed?",
      "Wat is het raarste excuus dat je ooit hebt verzonnen?",
      "Heb je ooit iemands geheim doorverteld?",
      "Wat is het meest cringy openingszin die ooit tegen je is gebruikt?",
      "Wat is het raarste wat je ooit hebt opgezocht op internet?",
      "Wat is de domste reden waarom je ooit ruzie hebt gehad?",
      "Heb je ooit gedaan alsof je ziek was om onder iets uit te komen?",
      "Wat is het meest onverwachte dat je ooit in iemand aantrok?",
      "Heb je ooit iemand geghost? Waarom?",
      "Wat is je grootste onzekerheid?",
      "Heb je ooit een weddenschap verloren en moest je iets gênants doen?",
      "Wat is het grappigste wat je ooit in een openbaar toilet hebt gehoord?",
      "Wat is de gekste manier waarop je ooit iemands aandacht hebt proberen te trekken?",
      "Heb je ooit een privégesprek per ongeluk met iemand gedeeld?",
      "Wat is het domste dat je ooit in een dronken bui hebt beloofd?",
      "Heb je ooit gedaan alsof je een bericht niet hebt gezien terwijl je dat wel had?",
      "Wat is het meest ongemakkelijke moment dat je met je ex hebt gehad?",
      "Wat is de meest gênante bijnaam die je ooit hebt gehad?",
      "Wat is de domste fout die je ooit in een relatie hebt gemaakt?",
      "Heb je ooit in de problemen gezeten door iets wat je op social media hebt geplaatst?",
      "Wat is de vreemdste versiertruc die ooit op jou is uitgeprobeerd?",
      "Wat is het meest gênante misverstand dat je ooit hebt gehad?",
      "Heb je ooit een romantisch gebaar gehad dat totaal verkeerd uitpakte?",
      "Heb je ooit gefaket dat je een talent had om indruk te maken op iemand?",
      "Wat is het meest ongemakkelijke familiegeheim dat je ooit hebt gehoord?",
      "Heb je ooit per ongeluk 'Ik hou van je' gezegd tegen de verkeerde persoon?",
      "Wat is het raarste dat je ooit in een hotelkamer hebt gevonden?",
      "Heb je ooit iemand laten geloven dat je iemand anders was?",
      "Heb je ooit iets gedaan om indruk te maken op iemand en werd het een ramp?",
      "Wat is de vreemdste plek waar je ooit bent wakker geworden?",
      "Heb je ooit een onverwachte gast betrapt in je huis?",
      "Wat is het raarste dat je ooit hebt moeten googelen?",
      "Heb je ooit een prank uitgehaald die totaal verkeerd ging?",
      "Wat is het ongemakkelijkste moment dat je met je schoonouders hebt gehad?",
      "Wat is het raarste wat je ooit in een restaurant hebt besteld?",
      "Heb je ooit een droom gehad die zo echt voelde dat je dacht dat het echt was?",
      "Wat is het gekste verhaal dat je ooit hebt gehoord dat daadwerkelijk waar bleek te zijn?",
      "Wat is het meest ongepaste moment waarop je hardop moest lachen?",
      "Heb je ooit een enorm domme fout gemaakt tijdens je werk of school?",
      "Wat is het gênantste wat je ooit tegen een crush hebt gezegd?",
      "Wat is het raarste dat iemand ooit in je DM’s heeft gestuurd?",
      "Heb je ooit iemand betrapt op iets waar ze zich enorm voor schaamden?",
      "Wat is het raarste cadeautje dat je ooit hebt gekregen?",
      "Wat is het meest beschamende wat je ooit tegen je baas of docent hebt gezegd?",
      "Heb je ooit je ouders betrapt op iets dat je liever niet had willen zien?",
      "Heb je ooit zo hard gelachen dat je iets uit je neus of mond spuwde?",
      "Wat is de domste beslissing die je ooit hebt genomen omdat je onder groepsdruk stond?",
      "Wat is het grootste geheim dat je ooit hebt bewaard?",
      "Heb je ooit iemand gelogen over hoe je je voelde om hun gevoelens te sparen?"
    ];  

const random = ["Wat zijn je hobby's?",
    "Verzamel je iets?",
    "Wat is uw passie?",
    "Wat is uw meest waardevolle bezit?",
    "Wat is de grootste prestatie van je leven?",
    "Wat staat er op uw bucketlist?",
    "Wat is uw favoriete recente herinnering?",
    "Wat is uw beste jeugdherinnering?",
    "Wat is uw favoriete feestdag?",
    "Wie kent u het beste?",
    "Met welk familielid sta je het dichtst bij?",
    "Welke vaardigheid zou je het liefst willen leren?",
    "Wat is de coolste plek waar je bent geweest?",
    "Hoe ziet je gemiddelde weekend eruit?",
    "Vertel me over je langst lopende vriendschap met iemand?",
    "Wat is je vroegste herinnering?",
    "Wat maakt jou uniek?",
    "Wie is je held?",
    "Wie is de slimste persoon die je ooit hebt ontmoet?",
    "Wat is één ding dat je dag onmiddellijk beter maakt?",
    "Wanneer voelde je je voor het eerst volwassen?",
    "Om wiens mening geef je het meest?",
    "Wat is de belangrijkste beslissing die je ooit hebt genomen?",
    "Afgezien van noodzakelijke dingen, welk ding zou je geen dag zonder kunnen?",
    "Waaraan geef je graag geld uit?",
    "Wat is iets dat je altijd doet glimlachen?",
    "Waar ben je het meest dankbaar voor?",
    "Waar kijk je het meest naar uit?",
    "Wat zou je willen dat meer mensen over je begrijpen?",
    "Wat is de grootste uitdaging of worsteling die je ooit bent aangegaan?",
    "Wat is het grootste risico dat je ooit hebt genomen?",
    "Wat is de meest belachelijke nachtmerrie die je ooit hebt gehad?",
    "Vertel ons een gênant verhaal.",
    "Vertel over een binnenpretje dat je met een vriend of familielid hebt.",
    "Als je huisdier kon praten, wat denk je dat het over jou zou zeggen?",
    "Vertel me je levensverhaal in precies één zin.",
    "Wat is het vreemdste toeval dat je ooit is overkomen?",
    "Wat is je favoriete willekeurige feit?",
    "Wat is je nutteloze talent?",
    "Wat is de vreemdste voedselcombinatie die je lekker vindt?",
    "Wat zou je drag queen naam zijn?",
    "Als je één superkracht mocht kiezen, wat zou dat dan zijn?",
    "Wat is je vreemdste irrationele angst?",
    "Beschrijf je meest excentrieke familielid.",
    "Heb je ooit een beroemdheid ontmoet? Welke beroemdheid zou je willen ontmoeten?",
    "Wat is het gekste dat je ooit hebt gedaan voor een uitdaging?",
    "Wat is het smerigste dat je zou doen voor 100 dollar?",
    "Welke liedjes staan op de soundtrack van je leven?",
    "Welke acteur zou je kiezen om jou te spelen in je biopic?",
    "Wat is je favoriete karaokeliedje?",
    "Als je een superheld was, wie zou dan je aartsvijand zijn?",
    "Creëer en beschrijf een undercover alias.",
    "Wat is je meest willekeurige impulsaankoop?",
    "Wat deed je als tiener waardoor je nu ineenkrimpt?",
    "Wat zou er op je waarschuwingslabel staan?",
    "Wat is je guilty pleasure?",
    "Welke emoji gebruik je het vaakst?",
    "Heeft je familie ongewone tradities?",
    "Een geest geeft je de mogelijkheid om oneindig veel van één ding te hebben. Wat is het?",
    "Wat is je favoriete willekeurige feit?",
    "Wat is je favoriete grap?",
    "Wat is het beste Halloween kostuum dat je ooit hebt gedragen?",
    "Wat is de vreemdste situatie waarin je je ooit bevond?",
    "Wat is het belachelijkste dat je als kind geloofde?",
    "Wat is de schandaligste leugen die je als kind hebt verteld?",
    "Wat is de domste manier waarop je jezelf hebt verwond?",
    "Hoe verspil je het vaakst tijd?",
    "Wat is de slechtste outfit die je ooit hebt gedragen?",
    "Heb je een partner?",
    "Heb je kinderen?",
    "Met wie woon je samen?",
    "Waar ben je opgegroeid?",
    "Wat is de beste plaats waar je ooit bent geweest?",
    "Wat denk je dat de meeste indruk zou maken op je vijfjarige zelf? Je 15-jarige zelf?",
    "Wat voor soort oudere persoon hoop je te zijn?",
    "Wat is je favoriete website?",
    "Wat is je favoriete seizoen?",
    "Welk boek heeft je leven veranderd?",
    "Hoe train je het liefst?",
    "Welke film zou je graag voor de eerste keer willen zien?",
    "Wat is een verhaal dat je graag vertelt, maar waar je zelden de kans voor krijgt?",
    "Welke vraag zou je willen dat mensen je vaker zouden stellen?",
    "Wat is een vraag die mensen je minder zouden willen stellen?",
    "Wat is je favoriete liedje?",
    "Wat was het eerste concert dat je bijwoonde? Het beste concert?",
    "Wat is je favoriete citaat?",
    "Wat is het laatste boek dat je gelezen hebt?",
    "Wat is de laatste TV show die je hebt gekeken?",
    "Welke film kun je uit je hoofd citeren?",
    "Wat vind je niet leuk en iedereen lijkt het leuk te vinden?",
    "Wat vind jij leuk en iedereen niet leuk?",
    "Wat maakt je het gelukkigst?",
    "Heb je ooit een beroemdheid ontmoet? Welke beroemdheid zou je willen ontmoeten?",
    "Beschrijf jezelf in drie woorden.",
    "Wat is het beste idee dat je ooit hebt gehad voor een bedrijf?",
    "Als je de kans zou krijgen, welk boek zou je dan schrijven?",
    "Wat is de vreemdste voedselcombinatie die je lekker vindt?",
    "Wat is je favoriete keuken?",
    "Wat is de beste maaltijd die je ooit hebt gegeten?",
    "Als je de loterij zou winnen, wat zou je dan als eerste doen?",
    "Wat is je favoriete cocktail?",
    "Heb je tatoeages? Zo niet, zijn er tatoeages die u zou willen?",
    "Waar ben je allergisch voor?",
    "Wat is uw favoriete kleur?",
    "Wat is uw favoriete dier?",
    "Heb je huisdieren?",
    "Heb je broers of zussen?",
    "Hoe oud ben je?",
    "Wanneer ben je jarig?",
    "Wat is het verst dat je van huis hebt gereisd?",
    "Wat is je favoriete zomeractiviteit?",
    "Wat is je favoriete winteractiviteit?",
    "Wat is je favoriete eten?",
    "Als je een nieuwe naam mocht kiezen, welke zou dat dan zijn?",
    "Wie is je favoriete superheld?",
    "Wie is je favoriete Disneyfiguur?",
    "Wat is de beste vakantie die je ooit hebt gehad?",
    "Wat is het domste dat je je kunt voorstellen?",
    "Waar ben je bang voor?",
    "Wat is je favoriete snack?",
    "Wat is je favoriete verhaal?",
    "Wat is het dapperste dat je ooit hebt gedaan?",
    "Wie is de beste stripfiguur?",
    "Als je één regel zou kunnen maken die iedereen in de wereld zou moeten volgen, wat zou die dan zijn?",
    "Als je eender welk dier als huisdier mocht hebben, wat zou je dan kiezen?",
    "Wat is het coolste dat je ooit hebt gemaakt?",
    "Wat is je favoriete manier om een middag door te brengen?",
    "Waar ben je nu het meest enthousiast over?",
    "Wat is je favoriete sport?",
    "Wat is je favoriete liedje?",
    "Laat me je beste danspas zien.",
    "Wat maakt je geweldig?",
    "Wat is je favoriete outfit?",
    "Als je je slaapkamer opnieuw mocht inrichten, wat zou je dan toevoegen?",
    "Beschrijf je favoriete knuffeldier.",
    "Wat is je favoriete speelgoed?",
    "Wat is je favoriete bezigheid met je ouders?",
    "Als je dertig seconden met één overledene zou kunnen praten, wie zou dat dan zijn en wat zou je zeggen?",
    "Als je naar het verleden kon reizen en één gebeurtenis kon veranderen, zou je dat doen? Welke? Waarom?",
    "Wat is het beste advies dat je ooit hebt gekregen?",
    "Wat is het slechtste advies dat je ooit hebt gekregen?",
    "Waar ben je in je leven het meest dankbaar voor?",
    "Als je iets zou kunnen veranderen aan de manier waarop je ouders je hebben opgevoed, wat zou dat dan zijn?",
    "Is er iets waar je al heel lang van droomt om te doen? Waarom heb je het nog niet gedaan?",
    "Als je wist dat je over een jaar plotseling zou sterven, zou je dan iets veranderen aan de manier waarop je nu leeft? Waarom?",
    "Welk deel van uw leven zou u het liefst willen verbeteren?",
    "Als je voor één dag van leven kon wisselen met iemand anders, wie zou je dan kiezen?",
    "Wat is uw definitie van succes?",
    "Hoe is uw kijk op de wereld in de loop der tijd veranderd?",
    "Geloof je dat mensen kunnen veranderen?",
    "Gelooft u dat u uw dromen zult verwezenlijken?",
    "Wat was het engste moment in je leven tot nu toe?",
    "Wat is je grootste spijt tot nu toe?",
    "Wiens dood heeft je het meest geraakt?",
    "Geloof je in de vrije wil?",
    "Geloof je in het lot?",
    "Als je één moment in je leven zou mogen herbeleven, welk zou dat dan zijn?",
    "Wat is uw meest gekoesterde geloof?",
    "Waar denk je dat we heengaan als we sterven?",
    "Wat is volgens u de zin van het leven?",
    "Wat is uw positie?",
    "Wat was je laatste functie?",
    "Wat was je eerste baan?",
    "Heb je gestudeerd? Zo ja, welke universiteit? Wat was uw hoofdvak?",
    "Werkt u beter 's ochtends of 's avonds?",
    "Werkt u liever op afstand of op kantoor?",
    "Werkt u liever in groepsverband of alleen?",
    "E-mailen, sms'en of bellen?",
    "Hoe drinkt u uw koffie?",
    "Wat is je grappigste werkverhaal tot nu toe?",
    "Wat was de grootste fout die je ooit op je werk hebt gemaakt?",
    "Wat was de moeilijkste les die je tot nu toe hebt geleerd?",
    "Beschrijf het beste team waarmee je hebt samengewerkt.",
    "Beschrijf de beste manager voor wie je hebt gewerkt.",
    "Wat is het beste teamuitje dat je ooit hebt bijgewoond?",
    "Wat is uw droomrol?",
    "Beschrijf de meest interessante collega met wie je hebt samengewerkt.",
    "Wat is uw favoriete project aller tijden?",
    "Als geld geen rol zou spelen, wat zou u dan doen met uw tijd?",
    "Als u niet in deze sector zou werken, welk vakgebied zou u dan kiezen?",
    "Beschrijf uw droombaas.",
    "Beschrijf uw nachtmerrie baas.",
    "Als u 500 jaar geleden zou leven, wat zou dan uw beroep zijn?",
    "Als u 500 jaar in de toekomst zou leven, wat zou uw beroep dan zijn?",
    "Wat hoop je dat je collega's over je zeggen op je pensioneringsfeest?",
    "Als geld geen rol zou spelen, hoe zou u uw tijd dan besteden?",
    "Waarom heb je dit beroep gekozen?",
    "Wat motiveert je?",
    "Wat inspireert u?",
    "Wat maakt je bang, professioneel gezien?",
    "Wat is uw droomproject?",
    "Noem je droomteam.",
    "Welk loopbaanadvies zou je aan je jongere zelf geven?",
    "Hoe gaat u om met werkstress?",
    "Je kunt één vraag voor altijd uit het interviewproces bannen. Welke kies je?",
    "Als u uw eigen bedrijf zou beginnen, wat voor soort bedrijf zou u dan oprichten?",
    "Zou je liever de loterij winnen of de perfecte baan hebben? Waarom?",
    "Wat is je favoriete manier om een vrije dag door te brengen?",
    "Wat vindt u uw beste kwaliteit?",
    "Wat zijn je ergernissen?",
    "Wat zou voor jou een \"perfecte\" dag zijn?",
    "Wat is jouw idee van een perfecte date?",
    "Noem een beroemdheid uit het heden of verleden.",
    "Wanneer heb je voor het laatst voor iemand gehuild?",
    "Wat is de eerste eigenschap die je in een potentiële partner ziet?",
    "Wat zijn de belangrijkste eigenschappen in potentiële partners?",
    "Wat zijn voor jou de belangrijkste aspecten van een relatie?",
    "Wat is het slechtste afspraakje dat je ooit hebt gehad?",
    "Wat is de beste date die je ooit hebt gehad?",
    "Wie zou u liever zien dat u op een blind date zet: vrienden, familieleden, collega's, professionele dating diensten, of willekeurige vreemden?",
    "Wat zijn voor jou belangrijke redenen om niet te daten?",
    "Hoe los je het liefst conflicten op?",
    "Wat was uw langste relatie?",
    "Hoe laat je mensen zien dat je van ze houdt?",
    "Gelooft u in zielsverwanten?",
    "Waar zie je jezelf over tien jaar?",
    "Wat is het meest spontane dat je ooit hebt gedaan?",
    "Wat zou je willen dat meer mensen over je begrepen?",
    "Wat is je slechtste gewoonte?",
    "Wat is je favoriete ding om met andere mensen te delen?",
    "Wat is een feit dat weinig mensen over je weten?",
    "Wat is de beste openingszin die je kent?",
    "Ben je ooit met een partner uitgegaan die je familie of vrienden niet mochten? Zo niet, zou je dat ooit doen?",
    "Ben je nog steeds bevriend met een van je exen?",
    "Heb je op slechte dagen graag dat anderen je opvrolijken of met rust laten?",
    "Waar is je gelukkige plek?",
    "Wat is je favoriete schoolvak?",
    "Doe je aan sport?",
    "Bespeel je een instrument?",
    "Doe je aan buitenschoolse activiteiten?",
    "Wat is je favoriete lunch?",
    "Wie is je favoriete leraar tot nu toe?",
    "Wat is het meest verrassende feit dat je hebt geleerd?",
    "Als je één ding aan school zou kunnen veranderen, wat zou dat dan zijn?",
    "Welke les zou je willen dat deze school aanbood?",
    "Werk je liever individueel of in groepjes?",
    "Zit je liever in bureaus, aan tafels, op de grond of in een zaal?",
    "Geeft u de voorkeur aan afstandsonderwijs of persoonlijk onderwijs?",
    "Wat is uw favoriete deel van school?",
    "Wat is je minst favoriete deel aan school?",
    "Wat is het meest interessante dat je ziet op weg naar school?",
    "Wat is je standaard ochtendroutine?",
    "Wat is het eerste wat u doet als u na school thuiskomt?",
    "Werk je? Zo ja, waar?",
    "Doe je vrijwilligerswerk? Zo ja, waar? Zo nee, waar zou je vrijwilligerswerk willen doen?",
    "Beschrijf je droomreis.",
    "Geef je de voorkeur aan schooluniformen of een ontspannen kledingcode?",
    "Spreek je nog andere talen? Welke talen zou je het liefst willen leren?",
    "Wat was het meest onverwachte dat je dit jaar op school hebt geleerd?",
    "Als ik je zou vragen om les te geven over een willekeurig onderwerp, welk onderwerp zou je dan kiezen?",
    "Wat is je beste studietip?",
    "Wat is het beste project dat je ooit hebt ingeleverd?",
    "Als je les kon krijgen van een willekeurige expert, wie zou je dan kiezen?",
    "Als je naar een willekeurige fictieve school zou kunnen gaan, welke zou je dan kiezen?",
    "Wat is je favoriete manier om een vrije dag door te brengen?",
    "Van welke muziek hou je?",
    "Wat was de beste vakantie die je ooit nam en waarom?",
    "Wat is de volgende plaats op je bucketlist en waarom?",
    "Wat zijn je hobby's en hoe ben je daarmee begonnen?",
    "Wat was je favoriete leeftijd toen je opgroeide?",
    "Wat was het laatste dat je hebt gelezen?",
    "Zou je zeggen dat je meer extrovert of introvert bent?",
    "Wat was de laatste TV show die je keek?",
    "Hou je van podcasts of luister je alleen naar muziek?",
    "Heb je een favoriete feestdag? Waarom of waarom niet?",
    "Als je de rest van je leven maar één voedsel zou mogen eten, wat zou dat dan zijn?",
    "Ga je graag naar de film of kijk je liever thuis?",
    "Wat is je goto guilty pleasure?",
    "Hoe oud was je toen je voor het eerst verliefd werd op een beroemdheid, en op wie?",
    "Wat is één ding dat je dag direct beter maakt?",
    "Heb je nog ergernissen?",
    "Welke maaltijd is je favoriet: ontbijt, lunch of diner?",
    "Welk liedje krijgt je altijd op de dansvloer?",
    "Welke activiteit brengt je onmiddellijk tot rust?",
    "Hoe zou jij je verjaardag het liefst doorbrengen?",
    "Wat doe je tijdens je woon-werkverkeer?",
    "Wat is je favoriete seizoen en waarom?",
    "Welke telefoon app gebruik je het meest?",
    "Zou je liever koken of bestellen?",
    "Wat is je favoriete bordspel?",
    "Hoe drink je je koffie?",
    "Wat is je meest waardevolle bezit en waarom?",
    "Wat is het eerste wat je zou doen als je de loterij zou winnen?",
    "Hoe breng je graag je tijd alleen door?",
    "Wat is het beste concert waar u ooit bent geweest?",
    "Heb je een favoriete vorm van lichaamsbeweging?",
    "Welke doelen zijn uw passie?",
    "Wat is uw favoriete genre (horror, scifi, romcom, enz.)?",
    "Wat is een essentieel onderdeel van je dagelijkse routine?",
    "Wat is het slechtste cadeau dat je ooit hebt gekregen en wat heb je eraan gedaan?",
    "Is er een baan die je nooit zou doen?",
    "Wat is het eerste wat je doet als je thuiskomt van je werk?",
    "Wie of wat inspireert u in uw carrière?",
    "Hoe pakt u het vrij nemen van werk aan?",
    "Wat is iets wat een buitenstaander niet zou weten over uw sector?",
    "Heb je een ochtendroutine op je werk? Zo ja, hoe ziet die eruit?",
    "Kunt u van thuis uit werken, en zo ja, vindt u dat leuk?",
    "Kunt u met al uw collega's overweg?",
    "Wat is uw favoriete ding aan uw huidige baan?",
    "Wat irriteert u het meest aan uw baan?",
    "Wat is het hoogtepunt in uw carrière waar u het meest trots op bent?",
    "Wat voor functie wilt u hierna uitoefenen?",
    "Ben je meer een \"werken om te leven\" of een \"leven om te werken\" type persoon?",
    "Geeft uw job u een gelukkig en voldaan gevoel? Waarom of waarom niet?",
    "Hoe zou uw 10-jarige zelf reageren op wat u nu doet?",
    "Wat herinnert u zich het meest van uw eerste baan?",
    "Hoe oud was je toen je begon te werken?",
    "Wat is de slechtste baan die je ooit hebt gehad?",
    "Waardoor raakte je oorspronkelijk geïnteresseerd in je huidige werkveld?",
    "Heb je ooit een bijbaantje gehad of overwogen?",
    "Wat is de beste carrièrebeslissing die je ooit hebt genomen?",
    "Wat is de slechtste carrièrebeslissing die je ooit hebt genomen?",
    "Vind je jezelf goed in netwerken?",
    "Welk loopbaanadvies zou je aan je jongere zelf geven?",
    "Gelooft u in een \"vijfjarenplan\"?",
    "Wanneer weet u dat u \"het gemaakt hebt\"?",
    "Kijk je uit naar je pensioen, of wil je zo lang mogelijk doorwerken?",
    "Heb je ooit last gehad van het \"imposter syndrome\"?",
    "Welke kwaliteiten zoekt u in een baas?",
    "Heeft u een professionele mentor? Zo niet, wilt u er een?",
    "Wat geeft u energie aan uw carrière?",
    "Houdt u van happy hours na het werk?",
    "Hoe motiveer je jezelf in je carrière?",
    "Toen u aan uw huidige baan begon, wat verraste u toen het meest?",
    "Hoe krabbel je weer op na een fout op het werk?",
    "Hoe ga je om met werkstress?",
    "Wat is één werkgerelateerd ding dat je het komende jaar wilt bereiken?",
    "Wie heeft de grootste invloed gehad op je beroepskeuze?",
    "Wat vindt je familie van je carrière?",
    "Als je het allemaal over kon doen, zou je dan dezelfde carrière nastreven? Waarom of waarom niet?",
    "Hoeveel tijd brengt u door met uw gezin?",
    "Met wie breng je het liefst tijd door en waarom?",
    "Welk familielid maakt het lekkerste eten?",
    "Hoe is uw mening over uw familie in de loop der jaren veranderd?",
    "Als je een hechte band met je familie hebt, wat is dan het moeilijkste als je niet bij ze bent?",
    "Had u graag een grotere familie gehad, of bent u tevreden met de huidige omvang?",
    "Welk familielid heeft de grootste invloed op je gehad?",
    "Wat is je favoriete verhaal over je grootouders?",
    "Heb je ooit je stamboom in kaart gebracht?",
    "Was je hecht met je familie toen je opgroeide?",
    "Bij wie in je familie voel je je het veiligst?",
    "Wil je een eigen familie?",
    "Als je je relatie met een familielid kon veranderen, zou je dat dan doen? Zo ja, met wie?",
    "Hoe was het om op te groeien als jongste/oudste/middelste/ enige kind?",
    "Wat is uw favoriete familieherinnering?",
    "Heb je ooit gewenst dat je anders was opgevoed?",
    "Wat is het beste advies dat een familielid je heeft gegeven?",
    "Zou je willen dat je meer broers en zussen had? Zo ja, waarom?",
    "Heb je ooit iets voor je ouders verborgen gehouden of tegen hen gelogen?",
    "Wat is je favoriete manier om tijd met je familie door te brengen?",
    "Hoe laat je je familie zien dat je van ze houdt?",
    "Wat is je favoriete familietraditie?",
    "Wat is de belangrijkste feestdag die je met je familie doorbrengt en waarom?",
    "Wat is iets wat uw familie zou verbazen als ze over u zouden horen?",
    "Welk familielid neem je het meest in vertrouwen?",
    "Hoe gaat u om met ruzies tussen familieleden?",
    "Als je kinderen hebt, hoe wil je ze opvoeden?",
    "Wat is belangrijker: familie of vrienden?",
    "Heb je vrienden die je als familie zou beschouwen?",
    "Welke fysieke eigenschappen deel je met je familieleden?",
    "Welke verhalen vertelden je familieleden je toen je opgroeide?",
    "Hoe hebben je ouders (en/of grootouders) elkaar ontmoet?",
    "Wat maakt je trots op je familie?",
    "Wat brengt je familie altijd samen?",
    "Wat maakt iemand volgens jou tot een \"goed mens\"?",
    "Geloof je in liefde op het eerste gezicht?",
    "Hoe toon je vriendelijkheid aan anderen?",
    "Geloof je in zielsverwanten? Waarom wel of niet?",
    "Wat zoek je in een vriendschap?",
    "Geloof je dat tijd die je graag verspilt geen verspilde tijd is?",
    "Welke levenslessen heb je op de harde manier moeten leren?",
    "Gelooft u dat wat voor u bestemd is, u nooit zal missen?",
    "Heb je ooit ware liefde ervaren, en hoe wist je dat?",
    "Wat is voor jou een relatiebreker?",
    "Als je maar één zintuig zou hebben (horen, voelen, zien, enz.), welke zou je dan willen hebben?",
    "Wat geeft je een vredig gevoel?",
    "Waardoor voel je je het meest bereikt?",
    "Zou je liever meer geld verdienen met een baan die je haat of minder met een baan waar je van houdt?",
    "Op welke van uw persoonlijkheidskenmerken bent u het meest trots?",
    "Wat is het eerste wat je zoekt in een partner en/of vriend?",
    "Leef je volgens een advies of motto?",
    "Hoe kan iemand jouw vertrouwen verdienen?",
    "Hoe kan iemand uw vertrouwen verliezen?",
    "Heb je liever dat iemand eerlijk is en je gevoelens kwetst of liegt om ze te beschermen?",
    "Als je met je vingers kon knippen en de wereld meteen beter kon maken, wat zou je dan doen?",
    "Geloof je in astrologie? Waarom of waarom niet?",
    "Heb je ooit een vriend verloren? Zo ja, wat is er gebeurd?",
    "Als je je (toekomstige) kind maar één ding zou kunnen leren, wat zou dat dan zijn?",
    "Wat is het engste wat je ooit hebt gedaan, en waarom heb je het gedaan?",
    "Geloof je in tweede kansen?",
    "Waar haal jij je nieuws vandaan?",
    "Wat is je grootste irrationele angst?",
    "Ben je actief op social media, of ben je liever wat meer op jezelf?",
    "Wat is uw definitie van succes?",
    "Ben je orgaandonor en hoe ben je tot die beslissing gekomen?",
    "Vind je dat je één ding per dag moet doen waar je bang voor bent?",
    "Wat denk je dat er gebeurt na de dood?",
    "Welke grens mag iemand bij jou nooit overschrijden?",
    "Hoe definieert u schoonheid?",
    "Gelooft u in leven op andere planeten?",
    "Hoe ga je om met iemand die het niet met je eens is?",
    "Denk je dat onze dromen verborgen betekenissen hebben?",
    "Als je wilt opgeven, wat houdt je dan op de been?",
    "Leef je volgens bepaalde wijze woorden?",
    "Hoe verander je een \"nee\" in een \"ja\"?",
    "Is het gemakkelijk voor u om hulp te aanvaarden bij het verwezenlijken van uw dromen?",
    "Als je iets anders zou kunnen doen dan wat je nu doet, wat zou je dan doen?",
    "Waarvan heb je spijt dat je het afgelopen jaar niets hebt gedaan?",
    "Wat staat er op je bucketlist?",
    "Als je onbeperkt geld had om je eigen bedrijf te beginnen, wat zou dat dan zijn?",
    "Als je zou weten dat vandaag je laatste dag op aarde was, wat zou je dan doen?",
    "Als je overal ter wereld zou kunnen wonen, waar zou dat dan zijn?",
    "Als je één moment in je leven zou mogen herbeleven, welk zou dat dan zijn?",
    "Als je de kans kreeg om onsterfelijk te zijn, zou je die dan nemen?",
    "Met welke beroemde persoon uit de geschiedenis zou je de dag willen doorbrengen?",
    "Als je kon tijdreizen, wanneer en waar zou je dan heengaan?",
    "Denk je dat je waarschijnlijk al je dromen zult verwezenlijken?",
    "Als je op magische wijze beroemd kon worden, zou je dat dan willen?",
    "Een geest geeft je drie wensen, wat zijn die?",
    "Geloof je in geesten - waarom of waarom niet? (Bonusvraag: Zo ja, ben je bang voor geesten?)",
    "Heb je speciale vaardigheden?",
    "Wat is je plan in een zombie-apocalyps?",
    "Kun je cursief schrijven?",
    "Als je in een film zou kunnen leven, welke zou dat dan zijn en waarom?",
    "Wat is jouw \"dans alsof niemand kijkt\" liedje?",
    "Zing je onder de douche?",
    "Hoeveel uur ben je op het vliegveld voor een vlucht?",
    "Als je een superkracht kon hebben, wat zou dat dan zijn?",
    "Als je in je volgende leven terug zou komen als een dier, welk dier zou je dan zijn?",
    "Wat zou de titel van je memoires zijn?",
    "Wat is het eerste wat je 's morgens doet?",
    "Wat is het laatste wat je 's avonds doet?",
    "Geloof je in complottheorieën (geen oordeel)?",
    "Wat is jouw idee van een perfecte date (ja, van het kalenderjaar)?",
    "Wat is de meest ongewone plek waar je in slaap bent gevallen?",
    "Waar kan iemand je op een feestje vinden?",
    "Was je je benen onder de douche?",
    "Wie zou jou spelen in de film van je leven?",
    "Heb je allergieën?",
    "Vertrouw je je eigen geheugen? Waarom of waarom niet?",
    "Met welk fictief personage voel je je het meest verbonden?",
    "Waarom zou je midden in een film weglopen?",
    "Wanneer heb je voor het laatst gehuild en waarom?",
    "Wat is je meest controversiële mening over iets alledaags?",
    "Ben je fan van beroemdheden?",
    "Wat is je favoriete middernachthapje?",
    "Wat is het vreemdste wat je doet als je alleen bent?",
    "Heb je terugkerende dromen?",
    "Wat is de ergste ruzie die je ooit hebt gehad?",
    "Wat is jouw mening over moderne kunst?",
    "Wat is de meest belachelijke outfit die je ooit hebt gedragen?",
    "Heb je liever dat je afwas of je kleren magisch schoon zijn?",
    "Wat is je favoriete verhaal over jezelf?",
    "Als je iets aan jezelf zou kunnen veranderen, zou je dat dan doen? Zo ja, wat en waarom?",
    "Wat was de beste nacht die je ooit met je partner hebt gehad?",
    "Heb je liever 's nachts, 's ochtends of halverwege de middag seks?",
    "Geef je liever of ontvang je liever?",
    "Zou je uitgaan met iemand die kleiner is dan jij?",
    "Heeft je vriend of vriendin je ooit in verlegenheid gebracht?",
    "Wat is het lekkerste om van het lichaam van je partner te likken?",
    "Waar ben je het meest bang voor in een relatie?",
    "Wat is je favoriete deel om gekust te worden?",
    "Denk je dat je met je huidige vriendin/vriendin zult trouwen?",
    "Hoe denk je over langeafstandsrelaties?",
    "Zou je kiezen voor een wilde, hete relatie of een rustige en stabiele?",
    "Hou je van knuffelen na intimiteit?",
    "Wat is volgens jou momenteel de grootste bedreiging voor het huwelijk?",
    "Wat is de grootste romantische mislukking die je ooit hebt meegemaakt?",
    "Heb je je partner ooit bedrogen?",
    "Wat is je favoriete lichaamsdeel van je partner?",
    "Hou je ervan als ik je haar naar achteren trek?",
    "Wat is het beste afspraakje dat je ooit hebt gehad?",
    "Heb je ooit in een \"vrienden met voordelen\" situatie gezeten?",
    "Wat is je grootste romantische mislukking?",
    "Als je elk wakker moment met je vriendin of vriend kon doorbrengen, zou je dat dan doen?",
    "Doe je graag je ogen dicht als ik over je hele lichaam kus?",
    "Ben je ooit op het eerste gezicht verliefd geweest?",
    "Zou je jezelf beschouwen als een romantische minnaar?",
    "Kun je raden wat ik nu draag?",
    "Heb je er ooit aan gedacht om je partner te bedriegen?",
    "Hou je ervan als ik je nek kus?",
    "Heb je je ooit aangetrokken gevoeld tot hetzelfde geslacht?",
    "Heb je ooit intimiteit ervaren zonder het te voelen?",
    "Hoe lang was je langste relatie?",
    "Ben je ooit bevriend geweest?",
    "Beschouw je jezelf als een geweldige of goede partner?",
    "Wat is uw grootste angst in een relatie?",
    "Neemt u liever de controle of bent u liever onderdanig?",
    "Wat baart u zorgen over het huwelijk?",
    "Hoe zou je het vinden om samen met je partner met iemand anders te zijn?",
    "Als u wist dat de vriend van uw vriendin haar bedroog, wat zou u dan doen?",
    "Ben je ooit verliefd geweest?",
    "Wie was je beste partner en waarom?",
    "Zou je ooit een langeafstandsrelatie aangaan?",
    "Maakt grootte echt uit?",
    "Zijn tweede rondes opwindend of vermoeiend?",
    "Heb je de doggy positie geprobeerd?",
    "Ben je luid of stil tijdens de seks?",
    "Zou je ooit met de beste vriend van je ex slapen?",
    "Wat is je favoriete lichaamsdeel bij een meisje/jongen?",
    "Zou je ooit overwegen te poseren voor de Playboy?",
    "Zou je nog steeds overwegen om intiem te worden als je ongesteld bent?",
    "Heb je het ooit in een auto gedaan?",
    "Wat is het verst dat je bent gegaan op een eerste date?",
    "Heeft iemand van jullie een naakt selfie gestuurd voordat jullie hier kwamen?",
    "Heb je pikante foto's of video's opgeslagen op je telefoon?",
    "Wat is jouw mening over vluggertjes?",
    "Heb je het ooit gedaan in het openbaar vervoer?",
    "Zou je je op je gemak voelen bij het masturberen in het bijzijn van je partner?",
    "Hebben je ouders je ooit de \"vogels en de bijen\" lezing gegeven?",
    "Ben je nog maagd?",
    "Wat vind je het aantrekkelijkst aan een man?",
    "Wat is je favoriete standje?",
    "Hoe zou je jezelf beoordelen op 10 in de slaapkamer?",
    "Wat is je wildste fantasie?",
    "Als je maar één persoon in deze kamer zou moeten flashen, wie zou dat dan zijn?",
    "Vrij je graag in openbare gelegenheden?",
    "Wat is de grootste fout die je in bed hebt gemaakt?",
    "Wat is het meest seksueel avontuurlijke dat je zou willen dat iemand met je deed?",
    "Heb je ooit iemand gesekst?",
    "Wat is het eerste wat je zou doen als je op een dag wakker zou worden als het andere geslacht?",
    "Neem je graag de leiding in de slaapkamer?",
    "Wat is jouw gebruikelijke stijl?",
    "Wat is je grootste seksuele angst?",
    "Wat is je voorkeur tussen mannen die de leiding nemen en vrouwen die de leiding nemen?",
    "Zou je graag iets vies doen in de badkuip?",
    "Wat is de krachtigste ervaring die je hebt gehad in de slaapkamer?",
    "Wat is het vreemdste dat jij en je partner ooit samen hebben gedaan?",
    "Wat is het meest avontuurlijke dat je in de slaapkamer hebt gedaan?",
    "Zou je ooit intiem zijn op de eerste date?",
    "Ben je liever bovenop of onderop?",
    "Met hoeveel mensen in je telefoonboek heb je gefantaseerd om naar bed te gaan?",
    "Uit wiens mond zou je alcohol willen nippen?",
    "Vind je het leuk als iemand vies tegen je praat?",
    "Wat is je grootste geheime verlangen?",
    "Wat is je langste droogteperiode?",
    "Heb je ooit gevoelens gehad voor iemand die bezet is?",
    "Zou je zeggen dat je kinky bent?",
    "Hoe zou je je uiterlijk beoordelen op een schaal van 1 tot 10?",
    "Hoeveel speeltjes voor volwassenen heb je eigenlijk?",
    "Zou je een jaar zonder telefoon kunnen als je daardoor met de persoon van je dromen zou kunnen trouwen?",
    "Heb je ooit problemen gehad met de politie?",
    "Windt buikdansen je op?",
    "Ben je ooit bij je ouders binnengelopen terwijl ze het deden?",
    "Heb je ooit aan een triootje gedacht in je leven?",
    "Lees je wel eens erotische fictie?",
    "Wat zijn jouw smerige waarheden?",
    "Wat is de kortste tijd die je nodig had om een orgasme te krijgen?",
    "Heb je ooit gelogen op je CV?",
    "Waar op je lichaam word je het liefst gemasseerd?",
    "Heb je ooit deelgenomen aan groepsseks?",
    "Heb je ooit naakt gezwommen?",
    "Wat is je favoriete speeltje in de slaapkamer?",
    "Heb je ooit de sms van een vriend genegeerd? Waarom deed je dat?",
    "Hoe vaak kijk je naar iets stouts?",
    "Wat is de grootste leugen die je ooit hebt verteld zonder betrapt te worden?",
    "Op welk deel van je lichaam zou je een tatoeage willen?",
    "Wat vind je van naaktstranden?",
    "Wat is jouw mening over anaal?",
    "Heb je ooit naakt rondgelopen in het openbaar?",
    "Slaap je in pyjama, ondergoed of helemaal niets?",
    "Zou je jezelf ooit filmen terwijl je het met iemand doet?",
    "Wat is het ergste wat je ooit door je ouders hebt laten doen?",
    "Welk ondeugend ding heb je ooit aan iemand voorgesteld en er bijna onmiddellijk spijt van gehad?",
    "Zou je een tandenborstel delen met je beste vriend?",
    "Zou je overwegen om van iemand je stoute slaaf voor de week te maken?",
    "Hoeveel meisjes heb je gehad?",
    "Slaap je meestal naakt?",
    "Wat is iets dat niemand anders over je weet?",
    "Heb je ooit bondage geprobeerd?",
    "Stalken meisjes jongens op sociale media?",
    "Als je beste vriendin B.O. had, zou je het haar vertellen?",
    "Als je het met één bekende zou mogen doen, wie zou dat dan zijn en waarom?",
    "Wat is je grootste onzekerheid?",
    "Ben je liever een jongen dan een meisje?",
    "Heb je ooit in het openbaar overgegeven?",
    "Heb je ooit een kostuum geleend voor een rollenspel?",
    "Heb je ooit geoefend met zoenen in een spiegel?",
    "Wat is het liedje waarop je het meest geilt?",
    "Heb je ooit de broer of zus van je vriend leuk gevonden?",
    "Wie was je slechtste kus ooit?",
    "Zou je liever leven zonder internet of zonder airco of verwarming?",
    "Wat is het meest walgelijke dat je ooit hebt gedaan?",
    "Zou je ooit naar een naaktresort of sauna gaan?",
    "Bewonder je jezelf wel eens in de spiegel?",
    "Wat was het ergste dat je ooit naar de verkeerde persoon hebt gestuurd?",
    "Ben je ooit in een stripclub geweest?",
    "Zou je liever mager en harig zijn of dik en glad?",
    "Heb je ooit een geheim verteld dat je beloofd had te bewaren?",
    "Heb je ooit gedaan alsof je een cadeau leuk vond? Hoe deed je alsof?",
    "Heb je ooit in je broek gepoept?",
    "Heb je ooit vuile waarheidspelletjes gespeeld met iemand?",
    "Heb je rare bijnamen?",
    "Wat zijn de beste emoji's die je gebruikt in een sexchat?",
    "Windt een duim in de lippen steken je op?",
    "Ga je ooit het huis uit zonder ondergoed aan?",
    "Wat was je eerste indruk van mij?",
    "Heb je ooit een garderobestoring gehad?",
    "Zou je ooit overwegen om met een compleet vreemde uit te gaan?",
    "Zou je tijdens een nachtje weg liever het bed delen met je beste vriendin of met haar vriend?",
    "Zou je ooit een schootdans willen ontvangen?",
    "Wat was de laatste R-rated film die je hebt gezien?",
    "Wat is mijn meest vervelende gewoonte?",
    "Denk je dat je knapper bent dan je beste vriendin?",
    "Heb je ooit een scheet gelaten en daarna iemand anders de schuld gegeven?",
    "Wat is het meest ongepaste moment dat je ooit hebt gelachen?",
    "Zou je liever je geslachtsorganen voor altijd verliezen of 200 pond aankomen?",
    "Heb je ooit betaald voor een porno abonnement?",
    "Heb je ooit eetbaar ondergoed geprobeerd?",
    "Denk je dat je zou kunnen acteren in een ondeugende filmscène?",
    "Heb je ooit zelf geplast?",
    "Wat is je favoriete smaak van condooms?",
    "Wat is je favoriete scheldwoord?",
    "Als ik zweet, is dat dan een opwinding of een afknapper?",
    "Heb je het ooit warm gehad in de douche terwijl je je lichaam wreef?",
    "Hou je ervan dat je kont gelikt wordt?",
    "Als je alles zou kunnen eten zonder dik te worden, wat zou dat dan zijn?",
    "Ben je ooit wakker geworden terwijl je op je kussen lag?",
    "Bedek je je ogen tijdens een eng gedeelte in een film?",
    "Zou je liever hondenvoer of kattenvoer eten?",
    "Heb je ooit het condoom van je tanden gerukt?",
    "Wat is het vreemdste dat je ooit hebt willen proberen tijdens het voorspel?",
    "Wanneer heb je voor het laatst in bed geplast?",
    "Wat is de langste tijd dat je in de badkamer bent gebleven, en waarom bleef je zo lang?",
    "Wat is het vervelendste aan je beste vriend?",
    "Wat is het smerigste dat uit je lichaam is gekomen?",
    "Heb je een slechte voetgeur?",
    "Heb je ooit oorsmeer geproefd?",
    "Wat doe je als je je nat voelt?",
    "Op wie ben je jaloers?",
    "Heb je ooit een vieze foto gezien op de telefoon van je ouders?",
    "Wat is een rare fantasie die je hebt?",
    "Wanneer heb je voor het laatst je tanden gepoetst?",
    "Wat voor x-rated films kijk je graag?",
    "Wat is het meest kinderachtige dat je nog steeds doet?",
    "Wat is het meest wanhopige dat je ooit hebt gedaan om op te vallen?",
    "Zou je liever een maand je haar niet wassen of een dag geen beha dragen?",
    "Wat is jouw mening over een meisje dat de eerste stap zet?",
    "Wat is de vreemdste plek waar je ooit seks hebt gehad?",
    "Als je kon reïncarneren in iemands lichaam, wie zou je dan willen worden?",
    "Is het beter om shampoo als zeep of zeep als shampoo te gebruiken?",
    "Wat is volgens jou de grootste afknapper?",
    "Vind je het leuk als mensen naar je kijken als je seks hebt?",
    "Heb je ooit een cheerleader willen zijn?",
    "Heb je ooit rare dingen gedaan terwijl je voor de spiegel stond?",
    "Vind je het leuk als iemand aan je haar trekt?",
    "Wat is je slechtste gewoonte?",
    "Heb je je ooit seksueel aangetrokken gevoeld tot anime figuren?",
    "Heb je ooit in een openbare ruimte naar porno gekeken?",
    "Wat is de vreemdste bijnaam die je hebt gekregen?",
    "Praat je wel eens tegen jezelf in de spiegel?",
    "Zou je je shirt een hele dag binnenstebuiten dragen als iemand je 100 dollar betaalde?",
    "Had je een denkbeeldig vriendje toen je opgroeide?",
    "Peuter je in je neus?",
    "Heeft iemand je ooit betrapt toen je naar de wc ging?",
    "Heb je ooit naar een meisje in bikini gekeken?",
    "Wanneer heb je voor het laatst gehuild?",
    "Heb je ooit iets stouts gedaan tijdens een videogesprek?",
    "Word je liever betrapt als je in je neus peutert of als je in een wedgie peutert?",
    "Wie is je minst favoriete persoon hier?",
    "Koop je liever speelgoed online of persoonlijk?",
    "Hoe lang heb je al niet gedoucht?",
    "Kwijl je in je slaap?",
    "Heb je een veiligheidsdeken?",
    "Draag je tighty-whities of oma slipjes?",
    "Welke leraar vind je het lekkerst?",
    "Ben je ooit betrapt toen je solo ging?",
    "Praat je in je slaap?",
    "Ben je ooit jaloers geweest in het openbaar?",
    "Wat was ons lastigste moment?",
    "Wat is het meest gênante dat je hebt gezegd of gedaan in het bijzijn van iemand die je leuk vindt?",
    "Wat heb je gezien waarvan je wou dat je het niet meer kon zien?",
    "Wat is het meest gênante dat je ooit hebt gedaan of gezegd op een date?",
    "Heb je ooit gezoend in de lift?",
    "Heb je accounts in een dating app?",
    "Wat is het meest gênante dat je hebt gedaan met betrekking tot je verliefdheid?",
    "Wat is het meest gênante dat je ouders je hebben zien doen?",
    "Slaap je met een knuffeldier?",
    "Heb je je ooit aangetrokken gevoeld tot hetzelfde geslacht?",
    "Heb je ooit luizen gehad?",
    "Heb je ooit iets gestolen van je werk?",
    "Heb je een geheim dagboek?",
    "Heb je ooit een naakte selfie ontvangen? Van wie was die?",
    "Dans je als je alleen bent?",
    "Wat was het laatste wat je zocht op je telefoon?",
    "Wat is voor jou een grote afknapper?",
    "Heb je ooit gevoelens gehad voor je beste vriend?",
    "Wanneer heb je voor het laatst in de spiegel gebogen?",
    "Heb je ooit een snotje geproefd?",
    "Wanneer ben je seksueel ontwaakt?",
    "Ben je ooit betrapt toen je iemand aan het bekijken was?",
    "Wat is het meest illegale dat je ooit hebt gedaan?",
    "Waar ben je het meest bang voor?",
    "Hoe denken jongens echt over menstruatie?"];

const bestfriend = [
    "Wat maakt jou het meest beschaamd?",
    "Wat is jouw liefdestaal?",
    "Hoe word je het liefst getroost als je verdrietig of van streek bent?",
    "Wat is je allerbeste herinnering?",
    "Waar hoop je over vijf jaar te zijn? Over tien? Over vijftien?",
    "Wanneer heb je je het meest uitgedaagd gevoeld?",
    "Ben je ooit gepest?",
    "Welke beroemdheid zou je als je andere beste vriend willen en waarom?",
    "Met welk familielid ben je het meest close?",
    "Wat doe je als niemand anders in de buurt is?",
    "Wat is één ding dat de meeste mensen niet over jou weten?",
    "Wat denk jij dat er gebeurt als we sterven?",
    "Wil je ooit kinderen? Hoeveel?",
    "Wat is de ergste verwonding die je ooit hebt gehad?",
    "Wat is je vroegste jeugdherinnering?",
    "Wat houdt je 's nachts wakker als je niet kan slapen?",
    "Wat is de laatste leugen die je hebt verteld?",
    "Wat is het mooiste compliment dat je ooit hebt gekregen?",
    "Wat beschouw jij als het ultieme comfortfood?",
    "Wat vind je je mooiste fysieke eigenschap?",
    "Wat zijn de drie dingen die jou het meeste stress bezorgen?",
    "Wat zijn de drie manieren waarop jij met stress omgaat?",
    "Als je maar drie dingen op je bucketlist mocht hebben, welke zouden dat zijn?",
    "Als je ooit zou trouwen, hoe ziet jouw droomaanzoek eruit?",
    "Wanneer heb je je het meest geliefd gevoeld?",
    "Als je een pretpark mocht ontwerpen, hoe zou het eruitzien?",
    "Wanneer was de laatste keer dat je je geïnspireerd voelde om iets te creëren?",
    "Heb je ooit een 'vriendschapsbreuk' meegemaakt? Wat heb je daarvan geleerd?",
    "Wie was je eerste vriend en is die nog steeds in je leven?",
    "Zou je ooit een langeafstandsrelatie overwegen?",
    "Wat vind jij de beste manier om conflicten op te lossen?",
    "Hoe hebben jouw ouders elkaar ontmoet?",
    "Vind je dat je een gezonde relatie hebt met sociale media?",
    "Wie was je favoriete leraar of lerares?",
    "Wat zijn je favoriete kindernamen?",
    "Is er een moment waarop ik je extra gesteund heb gevoeld?",
    "Hoe kan ik een betere vriend voor je zijn?",
    "Wat betekent vriendschap voor jou?"
  ];

const deep = [
    "Waar voel je je het meest schuldig over?",
    "Met wie zou je graag opnieuw contact willen?",
    "Wat bezorgt jou de meeste stress?",
    "Wanneer voel je je het meest alleen?",
    "Ben je ooit verliefd geweest?",
    "Geloof je in liefde op het eerste gezicht?",
    "Wat is de grootste les die je uit je laatste relatie hebt geleerd?",
    "Wat is één ding dat je aan jezelf zou willen veranderen?",
    "Aan wie zou je graag je excuses willen aanbieden?",
    "Wat was het laatste keerpunt in je leven?",
    "Wat helpt jou om door moeilijke dagen heen te komen?",
    "Bij wie voel je je het meest veilig?",
    "Wat is je favoriete jeugdherinnering?",
    "Wat is de grootste sprong in het diepe die je ooit hebt genomen?",
    "Naar wie kijk je het meest op en welke eigenschappen bewonder je in die persoon?",
    "Wat is je grootste angst?",
    "Wie was de laatste persoon die je aan het huilen bracht en waarom?",
    "Wanneer voelde je je het meest trots?",
    "Heb je ergens spijt van? Zo ja, waarvan?",
    "Wat is het mooiste cadeau dat je ooit hebt gekregen? Van wie was het en waarom was het zo speciaal?",
    "Als je één ding aan jezelf kon veranderen, wat zou het zijn?",
    "Geloof je in soulmates?",
    "Wat is het moeilijkste afscheid dat je ooit hebt moeten nemen?",
    "Wanneer was de laatste keer dat je jaloers was en waarom?",
    "Wat is de slechtste beslissing die je ooit hebt genomen?",
    "Hoe denk je dat je zal zijn op je oude dag?",
    "Wat is iets wat je als onvergeeflijk beschouwt?",
    "Geloof je in monogamie?"
  ];

const fun = [
    "Zou je liever een expert zijn in één ding, of best goed in veel dingen?",
    "Wat is je favoriete bezit en waarom?",
    "Heb je ooit je toekomst laten voorspellen?",
    "Bestel je liever eten of eet je liever buiten de deur?",
    "Wat is de eerste film die je je herinnert in de bioscoop te hebben gezien?",
    "Wat is je favoriete podcast?",
    "Wat was je meest twijfelachtige kapsel of modieuze keuze?",
    "Als geld geen rol speelde, wat zou je kopen?",
    "Waar droomde je afgelopen nacht over?",
    "Wanneer heb je in je leven het hardst gelachen?",
    "Wat doe je als niemand anders in de buurt is?",
    "Waar wil je het liefst naartoe reizen?",
    "Als je de rest van je leven maar één ding mocht eten, wat zou het zijn?",
    "Welk boek heeft de grootste impact op je gehad?",
    "Wat is je favoriete reclame?",
    "Welke eigenschappen trekken jou het meest aan in een liefdespartner?",
    "Je wint net €10.000—wat ga je ermee doen?",
    "Wat is het gelukkigste dat je ooit is overkomen?",
    "Wat is je favoriete manier om te sporten?",
    "Hou je van achtbanen?",
    "Wat is de klus in huis die je het meest haat, en waarom?",
    "Wat is je favoriete feestdag en waarom?",
    "Wat is de slechtste date die je ooit hebt gehad?",
    "Als je een tatoeage zou nemen, wat zou je kiezen en waarom?",
    "Als je drie wensen had, wat zou je wensen?",
    "Als je moest kiezen, zou je dan een hond of een kat nemen?",
    "Geloof je in buitenaards leven?",
    "Als je president zou zijn, wat is het eerste dat je zou veranderen in dit land?",
    "Als je in een ander tijdperk moest leven, welk tijdperk zou je kiezen?",
    "Wie was je allereerste crush?",
    "Welke vreemde taal zou je graag vloeiend willen spreken en waarom?",
    "Wat is je absolute favoriete dessert?",
    "Geloof je in geesten?",
    "Wat is je overlevingsplan tijdens een zombie-apocalyps?",
    "Als je een dier was, welk dier zou je zijn?",
    "Als je een alter ego moest creëren, wie zou dat zijn en hoe zou je hem of haar noemen?",
    "Wat is jouw nummer 1 karaoke-liedje?",
    "Ben je ooit op een blind date geweest?",
    "Wat was je eerste MSN-naam of e-mailadres?",
    "Wat is je favoriete willekeurige feitje?",
    "Wat was je eerste concert?",
    "Welke modeperiode had volgens jou de beste trends?",
    "Als er een liedje speelde elke keer dat je een kamer binnenkwam, welk liedje zou dat zijn?",
    "Wat is je huidverzorgingsroutine?",
    "Ben je ooit naar zomerkamp geweest?",
    "Wanneer was de laatste keer dat je echt de natuur hebt ervaren?",
    "Voel je je jong van geest, of juist een oude ziel?",
    "Wat betekent je naam en waarom hebben je ouders die gekozen?",
    "Welke onverwachte film maakt je altijd aan het huilen?"
  ];

const newfriend = [
    "Wat zijn je voornaamwoorden?",
    "Hoe zou jouw perfecte dag eruitzien? Plan hem van 's ochtends tot bedtijd.",
    "Wat is je sterrenbeeld?",
    "Wat is je Enneagram-type?",
    "Ben je op vakantie meer het type dat bij het zwembad relaxt of een avonturier die eropuit trekt?",
    "Beschouw je jezelf als religieus of spiritueel?",
    "Welke studierichting overweeg je en waarom?",
    "Als je maar naar één zanger of band mocht luisteren voor de rest van je leven, wie zou je kiezen?",
    "Wat is jouw go-to gerecht als je moet koken?",
    "Ben je bijgelovig?",
    "Wat is je favoriete bordspel?",
    "Wie is de beste filmvillain ooit?",
    "Wie is je favoriete persoon om te volgen op TikTok? En op Instagram?",
    "Had je als kind een denkbeeldige vriend?",
    "Als je jezelf in drie woorden moest omschrijven, welke zou je kiezen? Welke woorden zouden je vrienden voor jou kiezen?",
    "Heb je fobieën?",
    "Wat zijn jouw drie grootste ergernissen?",
    "Wat is je favoriete kleur en wat is je minst favoriete kleur?",
    "Hoe ziet jouw droomvakantie eruit?",
    "Ben je competitief?",
    "Wat is een moeilijke ervaring waar je van hebt geleerd en door bent gegroeid?",
    "Hoe is jouw relatie met je ouders?",
    "Volg je meestal je hart of je hoofd?",
    "Wat is het meest onverwachte of ongewone item op je bucketlist?",
    "Hoe was je laatste romantische relatie?",
    "Wat is een waarde waar je nooit op zou toegeven?",
    "Wat is je absolute droombaan?",
    "Als je een superkracht mocht kiezen, welke zou je nemen?",
    "Welke tv-show zet je op als je gewoon wilt ontspannen en je beter wilt voelen?",
    "Wat was de laatste film die je in de bioscoop hebt gezien?",
    "Als je kon tijdreizen, waar zou je naartoe gaan?",
    "Wat eet je meestal als ontbijt?",
    "Wat is je favoriete plant of bloem?",
    "Wat is je favoriete seizoen en waarom?",
    "Wie laat jou altijd lachen?",
    "Wat denk je dat jouw beste eigenschap is?",
    "Wat is jouw definitie van succes?",
    "Welke film heb je het vaakst gezien?",
    "Heb je verborgen talenten?",
    "Wat is de beste Halloween-outfit die je ooit hebt gedragen?",
    "Zou je liever aan de oceaan wonen of in de bergen?",
    "Wat is de langste reis die je ooit hebt gemaakt?",
    "Ben je meer een linkerhersenhelft- of rechterhersenhelft-persoon?",
    "Wat is je meest gebruikte emoji?",
    "Wat is een slechte gewoonte die je probeert af te leren?",
    "Wat is de engste film die je ooit hebt gezien?",
    "Ben je een ochtendmens of een nachtuil?",
    "Laad je het liefst op in je eentje of in gezelschap?",
    "Wat is het beste museum waar je ooit bent geweest?",
    "Wanneer kunnen we weer afspreken?"
  ];

export {
    juicy,
    random,
    bestfriend,
    deep,
    fun,
    newfriend
};